### PR TITLE
Onion2

### PR DESCRIPTION
**Pull request by IsaacLuo**
new features
=============
new menu style
block name on the menubar
enzyme sites
reverse CDS bars

### CODE REVIEW

**Comment by jlachoff** [comment]
Can someone please let me know when this is merged and live, so I can check it out?

**Comment by dchandran** [comment]
Just tested this branch. The restriction sites look nice. 

For some reason, switching to this branch caused my submodule to get detached and unable to update. I had to do git checkout 618f184864ac7a7b7c63a28da06a8662dbaf5409 manually inside the onion2 folder. I don't think is a problem with onion or this branch - it is something we are doing incorrectly with submodules.

**Comment by dchandran** [comment]
We should move to npm module based method for loading extensions. We should wait until that is done to merge this branch.

**Comment by maxbates** [comment]
closing, pending rebasing onto `npm-extensions`... can reopen when appropriate

**Pull request closed without merging**
