### PR TITLE
Store orchestrators + selectors

### PR DESCRIPTION
**Pull request by maxbates**

### CODE REVIEW

**Comment by maxbates** [comment]
@duncanmeech youll have to update a few of your actions potentially... dont need to pass blocks into the UI actions anymore... There may be some actions which are now 'selectors' - check `src/selectors/blocks` for the msot likely ones. WE can go through this tomorrow

**Comment by duncanmeech** [comment]
Lint issues:
/Users/meechd/dev/genome-designer/src/actions/blocks.js
  2:8  error  "uuid" is defined but never used  no-unused-vars

/Users/meechd/dev/genome-designer/src/actions/inspector.js
   2:8   error  "makeActionCreator" is defined but never used  no-unused-vars
  10:16  error  Missing trailing comma                         comma-dangle

/Users/meechd/dev/genome-designer/src/actions/inventory.js
  2:8  error  "makeActionCreator" is defined but never used  no-unused-vars

/Users/meechd/dev/genome-designer/src/actions/ui.js
  2:8  error  "makeActionCreator" is defined but never used  no-unused-vars

**Comment by duncanmeech** [comment]
I don't see any changes to spec files here. The tests all pass without changes?

**Comment by maxbates** [comment]
Tests should all pass, little about the interface to actions has changed

**Comment by maxbates** [comment]
@duncanmeech you ought to drink your own koolaid :)

**Comment by maxbates** [comment]
@duncanmeech ready for you

**Pull request merged**
