### PR TITLE
Seq viewer test

### PR DESCRIPTION
**Pull request by duncanmeech**
#### Overview

Adds a basic fabric test for the new sequence viewer

#### Type of change (bug fix, feature, docs, etc.)

e2e test ( also improvement to reset/forgot password test )

#### Requirements

- [x] Adds a test (for features + fixes)
- [ ] Docs updated (for features + fixes)

### CODE REVIEW

**Comment by maxbates** [comment]
I think we need a better solution for testing extensions. I dont think the tests belong in the main repo

**Comment by maxbates** [comment]
You can't test that it will be in the app, because there will be scenarios when it is not. E.g. user-preferences that specify not including it.

**Comment by duncanmeech** [comment]
..but we don't have that option right now. So testing in situ is appropriate.

**Comment by maxbates** [comment]
once user prefs are in (in the next week or so) you will have to fix this to check for it being present

**Pull request merged**
