### PR TITLE
Remove pip in package.json

### PR DESCRIPTION
**Pull request by dchandran**
@maxbates or @duncanmeech 

* Removed pip command in package.json. 
* Biopython needs to be installed separately for search or genbank import/export features to work. 
* Added pyc and storage to ignore list

### CODE REVIEW

**Comment by maxbates** [comment]
Should probably go in the Dockerfile?

**Comment by dchandran** [comment]
its already in the Dockerfile. I'll change it to python instead of python3 - done

**Comment by maxbates** [comment]
Biopython too?

**Comment by dchandran** [comment]
Yes, here are lines 23-26 of Dockerfile:
```
#everything needed by extensions
RUN apt-get install -y python python-pip
RUN yes | pip install biopython
```

**Pull request merged**
